# Generated by Django 2.2.6 on 2019-11-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
